version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: ideas_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_ideas
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    env_file:
      - .env-test
